version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: amartini1985/kittygram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/var/www/kittygram/media 
    depends_on:
      - db
  frontend:
    env_file: .env
    image: amartini1985/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: amartini1985/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/var/www/kittygram/media 
    ports:
      - 9000:80
    depends_on:
      - backend